// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'events.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `build_request_json`, `connect_to_gateway_with_sink`, `duration_to_std`, `encode_camera_snapshot`, `encode_frame_bytes`, `ensure_elevated_permission`, `next_request_id`, `outbound_request_sender_slot`, `parse_metadata`, `register_outbound_request_sender`, `try_emit`, `try_get_outbound_request_sender`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectionConfig`, `OutboundRequestSenderGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `add_event`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`


            Future<void>  sendGatewayRequestFrame({required String frameJson }) => RustLib.instance.api.crateApiConnectionSendGatewayRequestFrame(frameJson: frameJson);

Stream<GatewayEvent>  connectToGateway({required String url }) => RustLib.instance.api.crateApiConnectionConnectToGateway(url: url);

            
                abstract class EventSink {
                     Future<bool>  addEvent({required GatewayEvent event });


                }
                

class GatewayClient  {
                final String url;

                const GatewayClient({required this.url ,});

                 Future<String>  agentTurnRequest({required String requestId , required String message , String? model , String? thinking , BigInt? timeoutSeconds , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientAgentTurnRequest(that: this, requestId: requestId, message: message, model: model, thinking: thinking, timeoutSeconds: timeoutSeconds, sessionKey: sessionKey);


 Future<String>  cameraSnapRequest({required String requestId , required List<int> frameBytes , String? format , int? width , int? height , PlatformInt64? timestampMs , required bool compress , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientCameraSnapRequest(that: this, requestId: requestId, frameBytes: frameBytes, format: format, width: width, height: height, timestampMs: timestampMs, compress: compress, sessionKey: sessionKey);


 Future<String>  execCommandRequest({required String requestId , required String command , required List<String> args , Uint8List? stdinBytes , String? cwd , String? envJson , BigInt? timeoutMs , String? execId , bool? killOnDrop , bool? pty , int? cols , int? rows , String? term , String? permissionsJson , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientExecCommandRequest(that: this, requestId: requestId, command: command, args: args, stdinBytes: stdinBytes, cwd: cwd, envJson: envJson, timeoutMs: timeoutMs, execId: execId, killOnDrop: killOnDrop, pty: pty, cols: cols, rows: rows, term: term, permissionsJson: permissionsJson, sessionKey: sessionKey);


 Future<String>  execRequest({required String requestId , required String command , required List<String> args , String? cwd , String? envJson , String? stdin , BigInt? timeoutMs , bool? stream , String? execId , bool? killOnDrop , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientExecRequest(that: this, requestId: requestId, command: command, args: args, cwd: cwd, envJson: envJson, stdin: stdin, timeoutMs: timeoutMs, stream: stream, execId: execId, killOnDrop: killOnDrop, sessionKey: sessionKey);


 String  getUrl()=>RustLib.instance.api.crateApiConnectionGatewayClientGetUrl(that: this, );


 Future<String>  interactiveShellCloseRequest({required String requestId , String? streamId , String? reason , String? permissionsJson , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientInteractiveShellCloseRequest(that: this, requestId: requestId, streamId: streamId, reason: reason, permissionsJson: permissionsJson, sessionKey: sessionKey);


 Future<String>  interactiveShellOpenRequest({required String requestId , int? cols , int? rows , String? term , String? metadataJson , String? permissionsJson , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientInteractiveShellOpenRequest(that: this, requestId: requestId, cols: cols, rows: rows, term: term, metadataJson: metadataJson, permissionsJson: permissionsJson, sessionKey: sessionKey);


 Future<String>  interactiveShellResizeRequest({required String requestId , String? streamId , required int cols , required int rows , String? permissionsJson , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientInteractiveShellResizeRequest(that: this, requestId: requestId, streamId: streamId, cols: cols, rows: rows, permissionsJson: permissionsJson, sessionKey: sessionKey);


 Future<String>  interactiveShellSendRequest({required String requestId , String? streamId , required List<int> inputBytes , String? channel , String? permissionsJson , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientInteractiveShellSendRequest(that: this, requestId: requestId, streamId: streamId, inputBytes: inputBytes, channel: channel, permissionsJson: permissionsJson, sessionKey: sessionKey);


 Future<String>  logsSubscribeRequest({required String requestId , String? level , int? tail , PlatformInt64? since , bool? includeInternal , String? filtersJson , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientLogsSubscribeRequest(that: this, requestId: requestId, level: level, tail: tail, since: since, includeInternal: includeInternal, filtersJson: filtersJson, sessionKey: sessionKey);


 Future<String>  logsUnsubscribeRequest({required String requestId , String? subscriptionId , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientLogsUnsubscribeRequest(that: this, requestId: requestId, subscriptionId: subscriptionId, sessionKey: sessionKey);


  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
static Future<GatewayClient>  newInstance({required String url })=>RustLib.instance.api.crateApiConnectionGatewayClientNew(url: url);


 String  nextRequestId()=>RustLib.instance.api.crateApiConnectionGatewayClientNextRequestId(that: this, );


 Future<String>  sessionsCloseRequest({required String requestId , required String sessionKey , String? reason , String? metadataJson })=>RustLib.instance.api.crateApiConnectionGatewayClientSessionsCloseRequest(that: this, requestId: requestId, sessionKey: sessionKey, reason: reason, metadataJson: metadataJson);


 Future<String>  sessionsListRequest({required String requestId , int? limit , String? cursor , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientSessionsListRequest(that: this, requestId: requestId, limit: limit, cursor: cursor, sessionKey: sessionKey);


 Future<String>  sessionsSpawnRequest({required String requestId , String? parentSessionKey , String? label , String? metadataJson , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientSessionsSpawnRequest(that: this, requestId: requestId, parentSessionKey: parentSessionKey, label: label, metadataJson: metadataJson, sessionKey: sessionKey);


 Future<String>  systemEventRequest({required String requestId , String? text , String? mode , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientSystemEventRequest(that: this, requestId: requestId, text: text, mode: mode, sessionKey: sessionKey);


 Future<String>  systemProbeRequest({required String requestId , bool? network , bool? disk , bool? gateway , String? sessionKey })=>RustLib.instance.api.crateApiConnectionGatewayClientSystemProbeRequest(that: this, requestId: requestId, network: network, disk: disk, gateway: gateway, sessionKey: sessionKey);


                

                
        @override
        int get hashCode => url.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is GatewayClient &&
                runtimeType == other.runtimeType
                && url == other.url;
        
            }
            