// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `parse_error_payload`, `parse_event_payload`, `parse_payload`, `parse_request_params`, `parse_response_payload`, `scalar_field`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GatewayResponsePayload`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `into_dart`, `into_dart`, `into_dart`, `into_dart`, `into_into_dart`, `into_into_dart`, `into_into_dart`, `into_into_dart`, `sse_decode`, `sse_encode`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `new`


            Future<GatewayEvent?>  parseGatewayFrame({required String text }) => RustLib.instance.api.crateApiEventsParseGatewayFrame(text: text);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AgentTurn>>
                abstract class AgentTurn implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String get message;


 String? get model;


 String? get thinking;


 BigInt? get timeoutSeconds;


  set extra(BTreeMapStringValue extra);


  set message(String message);


  set model(String? model);


  set thinking(String? thinking);


  set timeoutSeconds(BigInt? timeoutSeconds);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CameraSnapshot>>
                abstract class CameraSnapshot implements RustOpaqueInterface {
                     String? get compression;


 String get data;


 String get encoding;


 BTreeMapStringValue get extra;


 String? get format;


 int? get height;


 PlatformInt64? get timestampMs;


 int? get width;


  set compression(String? compression);


  set data(String data);


  set encoding(String encoding);


  set extra(BTreeMapStringValue extra);


  set format(String? format);


  set height(int? height);


  set timestampMs(PlatformInt64? timestampMs);


  set width(int? width);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectAuth>>
                abstract class ConnectAuth implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String? get password;


 String? get token;


  set extra(BTreeMapStringValue extra);


  set password(String? password);


  set token(String? token);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectChallenge>>
                abstract class ConnectChallenge implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String get nonce;


 PlatformInt64 get ts;


  set extra(BTreeMapStringValue extra);


  set nonce(String nonce);


  set ts(PlatformInt64 ts);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectClient>>
                abstract class ConnectClient implements RustOpaqueInterface {
                     String? get deviceFamily;


 String? get displayName;


 BTreeMapStringValue get extra;


 String get id;


 String? get instanceId;


 String? get mode;


 String? get modelIdentifier;


 String? get platform;


 String? get version;


  set deviceFamily(String? deviceFamily);


  set displayName(String? displayName);


  set extra(BTreeMapStringValue extra);


  set id(String id);


  set instanceId(String? instanceId);


  set mode(String? mode);


  set modelIdentifier(String? modelIdentifier);


  set platform(String? platform);


  set version(String? version);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectDevice>>
                abstract class ConnectDevice implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String? get id;


 String? get nonce;


 String? get publicKey;


 String? get signature;


 PlatformInt64? get signedAt;


  set extra(BTreeMapStringValue extra);


  set id(String? id);


  set nonce(String? nonce);


  set publicKey(String? publicKey);


  set signature(String? signature);


  set signedAt(PlatformInt64? signedAt);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectParams>>
                abstract class ConnectParams implements RustOpaqueInterface {
                     ConnectAuth? get auth;


 List<String> get caps;


 ConnectClient? get client;


 List<String> get commands;


 ConnectDevice? get device;


 BTreeMapStringValue get extra;


 String? get locale;


 int? get maxProtocol;


 int? get minProtocol;


 BTreeMapStringBool get permissions;


 String? get role;


 List<String> get scopes;


 String? get userAgent;


  set auth(ConnectAuth? auth);


  set caps(List<String> caps);


  set client(ConnectClient? client);


  set commands(List<String> commands);


  set device(ConnectDevice? device);


  set extra(BTreeMapStringValue extra);


  set locale(String? locale);


  set maxProtocol(int? maxProtocol);


  set minProtocol(int? minProtocol);


  set permissions(BTreeMapStringBool permissions);


  set role(String? role);


  set scopes(List<String> scopes);


  set userAgent(String? userAgent);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ExecOutput>>
                abstract class ExecOutput implements RustOpaqueInterface {
                     String? get data;


 String? get encoding;


 bool? get eof;


 String? get execId;


 int? get exitCode;


 BTreeMapStringValue get extra;


 String? get stream;


 PlatformInt64? get timestampMs;


  set data(String? data);


  set encoding(String? encoding);


  set eof(bool? eof);


  set execId(String? execId);


  set exitCode(int? exitCode);


  set extra(BTreeMapStringValue extra);


  set stream(String? stream);


  set timestampMs(PlatformInt64? timestampMs);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ExecParams>>
                abstract class ExecParams implements RustOpaqueInterface {
                     List<String> get args;


 String get command;


 String? get cwd;


 BTreeMapStringValue? get env;


 String? get execId;


 BTreeMapStringValue get extra;


 bool? get killOnDrop;


 String? get stdin;


 bool? get stream;


 BigInt? get timeoutMs;


  set args(List<String> args);


  set command(String command);


  set cwd(String? cwd);


  set env(BTreeMapStringValue? env);


  set execId(String? execId);


  set extra(BTreeMapStringValue extra);


  set killOnDrop(bool? killOnDrop);


  set stdin(String? stdin);


  set stream(bool? stream);


  set timeoutMs(BigInt? timeoutMs);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GatewayError>>
                abstract class GatewayError implements RustOpaqueInterface {
                     String? get code;


 Value? get details;


 BTreeMapStringValue get extra;


 String? get message;


 BigInt? get retryAfterMs;


 bool? get retryable;


  set code(String? code);


  set details(Value? details);


  set extra(BTreeMapStringValue extra);


  set message(String? message);


  set retryAfterMs(BigInt? retryAfterMs);


  set retryable(bool? retryable);


static Future<GatewayError>  default_()=>RustLib.instance.api.crateApiEventsGatewayErrorDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GatewayEvent>>
                abstract class GatewayEvent implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GatewayEventPayload>>
                abstract class GatewayEventPayload implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GatewayRequestFrame>>
                abstract class GatewayRequestFrame implements RustOpaqueInterface {
                     String get frameType;


 String get id;


 String get method;


 GatewayRequestParams get params;


 String? get sessionKey;


  set frameType(String frameType);


  set id(String id);


  set method(String method);


  set params(GatewayRequestParams params);


  set sessionKey(String? sessionKey);


 Future<String>  toJson();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GatewayRequestParams>>
                abstract class GatewayRequestParams implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HelloAuth>>
                abstract class HelloAuth implements RustOpaqueInterface {
                     String? get deviceToken;


 BTreeMapStringValue get extra;


 String? get role;


 List<String> get scopes;


  set deviceToken(String? deviceToken);


  set extra(BTreeMapStringValue extra);


  set role(String? role);


  set scopes(List<String> scopes);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HelloOk>>
                abstract class HelloOk implements RustOpaqueInterface {
                     HelloAuth? get auth;


 BTreeMapStringValue get extra;


 String get payloadType;


 HelloPolicy? get policy;


 int? get protocol;


  set auth(HelloAuth? auth);


  set extra(BTreeMapStringValue extra);


  set payloadType(String payloadType);


  set policy(HelloPolicy? policy);


  set protocol(int? protocol);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HelloPolicy>>
                abstract class HelloPolicy implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 BigInt? get tickIntervalMs;


  set extra(BTreeMapStringValue extra);


  set tickIntervalMs(BigInt? tickIntervalMs);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LogEntry>>
                abstract class LogEntry implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 BTreeMapStringValue? get fields;


 String? get level;


 String? get message;


 Value? get span;


 List<Value> get spans;


 String? get target;


 BigInt? get threadId;


 String? get threadName;


 String? get timestamp;


 PlatformInt64? get ts;


  set extra(BTreeMapStringValue extra);


  set fields(BTreeMapStringValue? fields);


  set level(String? level);


  set message(String? message);


  set span(Value? span);


  set spans(List<Value> spans);


  set target(String? target);


  set threadId(BigInt? threadId);


  set threadName(String? threadName);


  set timestamp(String? timestamp);


  set ts(PlatformInt64? ts);


static Future<LogEntry>  default_()=>RustLib.instance.api.crateApiEventsLogEntryDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LogsEvent>>
                abstract class LogsEvent implements RustOpaqueInterface {
                     List<LogEntry> get entries;


 LogEntry? get entry;


 BTreeMapStringValue get extra;


 String? get subscriptionId;


  set entries(List<LogEntry> entries);


  set entry(LogEntry? entry);


  set extra(BTreeMapStringValue extra);


  set subscriptionId(String? subscriptionId);


static Future<LogsEvent>  default_()=>RustLib.instance.api.crateApiEventsLogsEventDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LogsSubscribeParams>>
                abstract class LogsSubscribeParams implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 BTreeMapStringValue? get filters;


 bool? get includeInternal;


 String? get level;


 PlatformInt64? get since;


 int? get tail;


  set extra(BTreeMapStringValue extra);


  set filters(BTreeMapStringValue? filters);


  set includeInternal(bool? includeInternal);


  set level(String? level);


  set since(PlatformInt64? since);


  set tail(int? tail);


static Future<LogsSubscribeParams>  default_()=>RustLib.instance.api.crateApiEventsLogsSubscribeParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LogsUnsubscribeParams>>
                abstract class LogsUnsubscribeParams implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String? get subscriptionId;


  set extra(BTreeMapStringValue extra);


  set subscriptionId(String? subscriptionId);


static Future<LogsUnsubscribeParams>  default_()=>RustLib.instance.api.crateApiEventsLogsUnsubscribeParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaEvent>>
                abstract class MediaEvent implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PresenceEntry>>
                abstract class PresenceEntry implements RustOpaqueInterface {
                     String? get deviceFamily;


 BTreeMapStringValue get extra;


 String? get host;


 String? get instanceId;


 String? get ip;


 BigInt? get lastInputSeconds;


 String? get mode;


 String? get modelIdentifier;


 String? get reason;


 List<String> get tags;


 PlatformInt64? get ts;


 String? get version;


  set deviceFamily(String? deviceFamily);


  set extra(BTreeMapStringValue extra);


  set host(String? host);


  set instanceId(String? instanceId);


  set ip(String? ip);


  set lastInputSeconds(BigInt? lastInputSeconds);


  set mode(String? mode);


  set modelIdentifier(String? modelIdentifier);


  set reason(String? reason);


  set tags(List<String> tags);


  set ts(PlatformInt64? ts);


  set version(String? version);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PresenceEvent>>
                abstract class PresenceEvent implements RustOpaqueInterface {
                     List<PresenceEntry> get entries;


 BTreeMapStringValue get extra;


  set entries(List<PresenceEntry> entries);


  set extra(BTreeMapStringValue extra);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionsCloseParams>>
                abstract class SessionsCloseParams implements RustOpaqueInterface {
                     bool get archive;


 BTreeMapStringValue get extra;


 BTreeMapStringValue? get metadata;


 String? get reason;


 String get sessionKey;


  set archive(bool archive);


  set extra(BTreeMapStringValue extra);


  set metadata(BTreeMapStringValue? metadata);


  set reason(String? reason);


  set sessionKey(String sessionKey);


static Future<SessionsCloseParams>  default_()=>RustLib.instance.api.crateApiEventsSessionsCloseParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionsListParams>>
                abstract class SessionsListParams implements RustOpaqueInterface {
                     String? get cursor;


 BTreeMapStringValue get extra;


 int? get limit;


  set cursor(String? cursor);


  set extra(BTreeMapStringValue extra);


  set limit(int? limit);


static Future<SessionsListParams>  default_()=>RustLib.instance.api.crateApiEventsSessionsListParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionsSpawnParams>>
                abstract class SessionsSpawnParams implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String? get label;


 BTreeMapStringValue? get metadata;


 String? get parentSessionKey;


  set extra(BTreeMapStringValue extra);


  set label(String? label);


  set metadata(BTreeMapStringValue? metadata);


  set parentSessionKey(String? parentSessionKey);


static Future<SessionsSpawnParams>  default_()=>RustLib.instance.api.crateApiEventsSessionsSpawnParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ShutdownEvent>>
                abstract class ShutdownEvent implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String? get reason;


 BigInt? get restartExpectedMs;


  set extra(BTreeMapStringValue extra);


  set reason(String? reason);


  set restartExpectedMs(BigInt? restartExpectedMs);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamCloseParams>>
                abstract class StreamCloseParams implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String? get reason;


 String get stream;


 String? get streamId;


  set extra(BTreeMapStringValue extra);


  set reason(String? reason);


  set stream(String stream);


  set streamId(String? streamId);


static Future<StreamCloseParams>  default_()=>RustLib.instance.api.crateApiEventsStreamCloseParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamClosedEvent>>
                abstract class StreamClosedEvent implements RustOpaqueInterface {
                     int? get exitCode;


 BTreeMapStringValue get extra;


 String? get reason;


 String get stream;


 String? get streamId;


  set exitCode(int? exitCode);


  set extra(BTreeMapStringValue extra);


  set reason(String? reason);


  set stream(String stream);


  set streamId(String? streamId);


static Future<StreamClosedEvent>  default_()=>RustLib.instance.api.crateApiEventsStreamClosedEventDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamDataEvent>>
                abstract class StreamDataEvent implements RustOpaqueInterface {
                     String? get channel;


 int? get cols;


 String? get data;


 String? get encoding;


 BTreeMapStringValue get extra;


 int? get rows;


 String get stream;


 String? get streamId;


 PlatformInt64? get timestampMs;


  set channel(String? channel);


  set cols(int? cols);


  set data(String? data);


  set encoding(String? encoding);


  set extra(BTreeMapStringValue extra);


  set rows(int? rows);


  set stream(String stream);


  set streamId(String? streamId);


  set timestampMs(PlatformInt64? timestampMs);


static Future<StreamDataEvent>  default_()=>RustLib.instance.api.crateApiEventsStreamDataEventDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamOpenParams>>
                abstract class StreamOpenParams implements RustOpaqueInterface {
                     int? get cols;


 BTreeMapStringValue get extra;


 BTreeMapStringValue? get metadata;


 int? get rows;


 String get stream;


 String? get term;


  set cols(int? cols);


  set extra(BTreeMapStringValue extra);


  set metadata(BTreeMapStringValue? metadata);


  set rows(int? rows);


  set stream(String stream);


  set term(String? term);


static Future<StreamOpenParams>  default_()=>RustLib.instance.api.crateApiEventsStreamOpenParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamSendParams>>
                abstract class StreamSendParams implements RustOpaqueInterface {
                     String? get channel;


 int? get cols;


 String? get data;


 String? get encoding;


 String? get event;


 BTreeMapStringValue get extra;


 int? get rows;


 String get stream;


 String? get streamId;


  set channel(String? channel);


  set cols(int? cols);


  set data(String? data);


  set encoding(String? encoding);


  set event(String? event);


  set extra(BTreeMapStringValue extra);


  set rows(int? rows);


  set stream(String stream);


  set streamId(String? streamId);


static Future<StreamSendParams>  default_()=>RustLib.instance.api.crateApiEventsStreamSendParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SystemEvent>>
                abstract class SystemEvent implements RustOpaqueInterface {
                     BTreeMapStringValue get extra;


 String? get mode;


 String? get sessionKey;


 String? get text;


  set extra(BTreeMapStringValue extra);


  set mode(String? mode);


  set sessionKey(String? sessionKey);


  set text(String? text);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SystemProbeCheck>>
                abstract class SystemProbeCheck implements RustOpaqueInterface {
                     Value? get details;


 BTreeMapStringValue get extra;


 BigInt? get latencyMs;


 String? get message;


 bool? get ok;


  set details(Value? details);


  set extra(BTreeMapStringValue extra);


  set latencyMs(BigInt? latencyMs);


  set message(String? message);


  set ok(bool? ok);


static Future<SystemProbeCheck>  default_()=>RustLib.instance.api.crateApiEventsSystemProbeCheckDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SystemProbeParams>>
                abstract class SystemProbeParams implements RustOpaqueInterface {
                     bool? get disk;


 BTreeMapStringValue get extra;


 bool? get gateway;


 bool? get network;


  set disk(bool? disk);


  set extra(BTreeMapStringValue extra);


  set gateway(bool? gateway);


  set network(bool? network);


static Future<SystemProbeParams>  default_()=>RustLib.instance.api.crateApiEventsSystemProbeParamsDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SystemProbeResult>>
                abstract class SystemProbeResult implements RustOpaqueInterface {
                     SystemProbeCheck? get disk;


 BTreeMapStringValue get extra;


 SystemProbeCheck? get gateway;


 SystemProbeCheck? get network;


  set disk(SystemProbeCheck? disk);


  set extra(BTreeMapStringValue extra);


  set gateway(SystemProbeCheck? gateway);


  set network(SystemProbeCheck? network);


static Future<SystemProbeResult>  default_()=>RustLib.instance.api.crateApiEventsSystemProbeResultDefault();



                    
                }
                
            