// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `decode_output_data`, `emit_exec_output`, `send_request_and_wait_response`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`


            Stream<TerminalChunk>  execCommand({required String url , required String command , String? cwd , BigInt? timeoutMs , String? sessionKey }) => RustLib.instance.api.crateApiTerminalExecCommand(url: url, command: command, cwd: cwd, timeoutMs: timeoutMs, sessionKey: sessionKey);

Future<String>  terminalStreamOpen({required String url , int? cols , int? rows , String? term , String? sessionKey }) => RustLib.instance.api.crateApiTerminalTerminalStreamOpen(url: url, cols: cols, rows: rows, term: term, sessionKey: sessionKey);

Future<void>  terminalStreamSend({required String url , required String streamId , required List<int> inputBytes , String? sessionKey }) => RustLib.instance.api.crateApiTerminalTerminalStreamSend(url: url, streamId: streamId, inputBytes: inputBytes, sessionKey: sessionKey);

            class TerminalChunk  {
                final String text;
final String kind;

                const TerminalChunk({required this.text ,required this.kind ,});

                
                

                
        @override
        int get hashCode => text.hashCode^kind.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is TerminalChunk &&
                runtimeType == other.runtimeType
                && text == other.text&& kind == other.kind;
        
            }
            